### ISSUE TITLE
[R-package] Add an R GPU job in CI

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#3780]
## Summary

CMake-based builds of the R package support building a GPU-accelerated version of LightGBM (https://github.com/microsoft/LightGBM/blob/master/R-package/README.md#installing-a-gpu-enabled-build).

This feature is not currently tested in a continuous integration (CI) job, but it should be.

## Motivation

The lack of automated tests for the R GPU package means it can be broken by changes in this repo, and we might not find out until those become user-facing issues (like the one reported in #3765 ).

## Description

To close this issue, add a job to https://github.com/microsoft/LightGBM/blob/706f2af7badc26f6ec68729469ec6ec79a66d802/.github/workflows/r_package.yml that installs with a command like `Rscript build_r.R --use-gpu` and then runs the R tests.

```yaml
          - os: ubuntu-latest
            task: r-package-gpu
            compiler: gcc
            r_version: 4.0
            build_type: cmake
```

## References

You might need to reuse of some of the GPU setup for the Python "gpu" tasks

* https://github.com/microsoft/LightGBM/blob/706f2af7badc26f6ec68729469ec6ec79a66d802/.ci/setup.sh#L67
* https://github.com/microsoft/LightGBM/blob/706f2af7badc26f6ec68729469ec6ec79a66d802/.ci/test.sh#L127
